### ISSUE TITLE
Ma questo Vue?

### ISSUE THREAD

**Issue by sensorario** [beerjs/faenza#1]
Ne sento tanto parlare e contemporaneamente non conosco (almeno credo) nessuno che lo usi. Qualcuno fa uso di questo framework? Pro? Contro? Chi ha voglia di parlarne un po?

**Comment by b4dnewz** [comment]
io ho incominciato ad usarlo in produzione e sarebbe SUPER fare un evento su vue!

il prox evento devo ancora aggiornarlo, c'è fra 2 settimane ed è chiamato: "Front-End Framework Comparisons" e indirettamente si parlerà anche di vue, essendo uno dei top framework nel 2017.

**Comment by b4dnewz** [comment]
Ho aggiornato le date nel commit 984d0ea977626de8bcae4e5d127230cd4bef0645 per il prossimo evento.

Il prossimo evento sarà **Comparison of Front-End Frameworks**
